export default [
  {
    gameNumber: 1,
    date: '16 Oct 2018',
    venue: 'vs',
    opponent: 'Oklahoma City Thunder',
    score: '108-100',
    win: true,
    difference: 8,
    pointsMadeByCurry: 32,
  },
  {
    gameNumber: 2,
    date: '19 Oct 2018',
    venue: '@',
    opponent: 'Utah Jazz',
    score: '124-123',
    win: true,
    difference: 1,
    pointsMadeByCurry: 31,
  },
  {
    gameNumber: 3,
    date: '21 Oct 2018',
    venue: '@',
    opponent: 'Denver Nuggets',
    score: '98-100',
    win: false,
    difference: 2,
    pointsMadeByCurry: 30,
  },
  {
    gameNumber: 4,
    date: '22 Oct 2018',
    venue: 'vs',
    opponent: 'Phoenix Suns',
    score: '123-103',
    win: true,
    difference: 20,
    pointsMadeByCurry: 29,
  },
  {
    gameNumber: 5,
    date: '24 Oct 2018',
    venue: 'vs',
    opponent: 'Washington Wizards',
    score: '144-122',
    win: true,
    difference: 22,
    pointsMadeByCurry: 51,
  },
  {
    gameNumber: 6,
    date: '26 Oct 2018',
    venue: '@',
    opponent: 'New York Knicks',
    score: '128-100',
    win: true,
    difference: 28,
    pointsMadeByCurry: 29,
  },
  {
    gameNumber: 7,
    date: '28 Oct 2018',
    venue: '@',
    opponent: 'Brooklyn Nets',
    score: '120-114',
    win: true,
    difference: 6,
    pointsMadeByCurry: 35,
  },
  {
    gameNumber: 8,
    date: '29 Oct 2018',
    venue: '@',
    opponent: 'Chicago Bulls',
    score: '149-124',
    win: true,
    difference: 25,
    pointsMadeByCurry: 23,
  },
  {
    gameNumber: 9,
    date: '31 Oct 2018',
    venue: 'vs',
    opponent: 'New Orleans Pelicans',
    score: '131-121',
    win: true,
    difference: 10,
    pointsMadeByCurry: 37,
  },
  {
    gameNumber: 10,
    date: '02 Nov 2018',
    venue: 'vs',
    opponent: 'Minnesota Timberwolves',
    score: '116-99',
    win: true,
    difference: 17,
    pointsMadeByCurry: 28,
  },
  {
    gameNumber: 11,
    date: '05 Nov 2018',
    venue: 'vs',
    opponent: 'Memphis Grizzlies',
    score: '117-101',
    win: true,
    difference: 16,
    pointsMadeByCurry: 19,
  },
  {
    gameNumber: 12,
    date: '08 Nov 2018',
    venue: 'vs',
    opponent: 'Milwaukee Bucks',
    score: '111-134',
    win: false,
    difference: 23,
    pointsMadeByCurry: 10,
  },
  {
    gameNumber: 13,
    date: '10 Nov 2018',
    venue: 'vs',
    opponent: 'Brooklyn Nets',
    score: '116-100',
    win: true,
    difference: 16,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 14,
    date: '12 Nov 2018',
    venue: '@',
    opponent: 'LA Clippers',
    score: '116-121',
    win: false,
    difference: 5,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 15,
    date: '13 Nov 2018',
    venue: 'vs',
    opponent: 'Atlanta Hawks',
    score: '110-103',
    win: true,
    difference: 7,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 16,
    date: '15 Nov 2018',
    venue: '@',
    opponent: 'Houston Rockets',
    score: '86-107',
    win: false,
    difference: 21,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 17,
    date: '17 Nov 2018',
    venue: '@',
    opponent: 'Dallas Mavericks',
    score: '109-112',
    win: false,
    difference: 3,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 18,
    date: '18 Nov 2018',
    venue: '@',
    opponent: 'San Antonio Spurs',
    score: '92-104',
    win: false,
    difference: 12,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 19,
    date: '21 Nov 2018',
    venue: 'vs',
    opponent: 'Oklahoma City Thunder',
    score: '95-123',
    win: false,
    difference: 28,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 20,
    date: '23 Nov 2018',
    venue: 'vs',
    opponent: 'Portland Trail Blazers',
    score: '125-97',
    win: true,
    difference: 28,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 21,
    date: '21 Nov 2018',
    venue: 'vs',
    opponent: 'Sacramento Kings',
    score: '117-116',
    win: true,
    difference: 1,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 22,
    date: '26 Nov 2018',
    venue: 'vs',
    opponent: 'Orlando Magic',
    score: '116-110',
    win: true,
    difference: 6,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 23,
    date: '29 Nov 2018',
    venue: '@',
    opponent: 'Toronto Raptors',
    score: '128-131',
    win: false,
    difference: 3,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 24,
    date: '01 Dec 2018',
    venue: '@',
    opponent: 'Detroit Pistons',
    score: '102-111',
    win: false,
    difference: 9,
    pointsMadeByCurry: 27,
  },
  {
    gameNumber: 25,
    date: '03 Dec 2018',
    venue: '@',
    opponent: 'Atlanta Hawks',
    score: '128-111',
    win: true,
    difference: 17,
    pointsMadeByCurry: 30,
  },
  {
    gameNumber: 26,
    date: '05 Dec 2018',
    venue: '@',
    opponent: 'Cleveland Cavaliers',
    score: '129-105',
    win: true,
    difference: 24,
    pointsMadeByCurry: 42,
  },
  {
    gameNumber: 27,
    date: '07 Dec 2018',
    venue: '@',
    opponent: 'Milwaukee Bucks',
    score: '105-95',
    win: true,
    difference: 10,
    pointsMadeByCurry: 20,
  },
  {
    gameNumber: 28,
    date: '10 Dec 2018',
    venue: 'vs',
    opponent: 'Minnesota Timberwolves',
    score: '116-108',
    win: true,
    difference: 8,
    pointsMadeByCurry: 38,
  },
  {
    gameNumber: 29,
    date: '12 Dec 2018',
    venue: 'vs',
    opponent: 'Toronto Raptors',
    score: '93-113',
    win: false,
    difference: 20,
    pointsMadeByCurry: 10,
  },
  {
    gameNumber: 30,
    date: '14 Dec 2018',
    venue: '@',
    opponent: 'Sacramento Kings',
    score: '130-125',
    win: true,
    difference: 5,
    pointsMadeByCurry: 35,
  },
  {
    gameNumber: 31,
    date: '17 Dec 2018',
    venue: 'vs',
    opponent: 'Memphis Grizzlies',
    score: '110-93',
    win: true,
    difference: 17,
    pointsMadeByCurry: 20,
  },
  {
    gameNumber: 32,
    date: '19 Dec 2018',
    venue: '@',
    opponent: 'Utah Jazz',
    score: '103-108',
    win: false,
    difference: 5,
    pointsMadeByCurry: 32,
  },
  {
    gameNumber: 33,
    date: '22 Dec 2018',
    venue: 'vs',
    opponent: 'Dallas Mavericks',
    score: '120-116',
    win: true,
    difference: 4,
    pointsMadeByCurry: 22,
  },
  {
    gameNumber: 34,
    date: '23 Dec 2018',
    venue: 'vs',
    opponent: 'LA Clippers',
    score: '129-127',
    win: true,
    difference: 2,
    pointsMadeByCurry: 42,
  },
  {
    gameNumber: 35,
    date: '25 Dec 2018',
    venue: 'vs',
    opponent: 'LA Lakers',
    score: '101-127',
    win: false,
    difference: 26,
    pointsMadeByCurry: 15,
  },
  {
    gameNumber: 36,
    date: '27 Dec 2018',
    venue: 'vs',
    opponent: 'Portland Trail Blazers',
    score: '109-110',
    win: false,
    difference: 1,
    pointsMadeByCurry: 29,
  },
  {
    gameNumber: 37,
    date: '29 Dec 2018',
    venue: '@',
    opponent: 'Portland Trail Blazers',
    score: '115-105',
    win: true,
    difference: 10,
    pointsMadeByCurry: 25,
  },
  {
    gameNumber: 38,
    date: '31 Dec 2018',
    venue: '@',
    opponent: 'Phoenix Suns',
    score: '132-109',
    win: true,
    difference: 23,
    pointsMadeByCurry: 34,
  },
  {
    gameNumber: 39,
    date: '03 Jan 2019',
    venue: 'vs',
    opponent: 'Houston Rockets',
    score: '134-135',
    win: false,
    difference: 1,
    pointsMadeByCurry: 35,
  },
  {
    gameNumber: 40,
    date: '05 Jan 2019',
    venue: '@',
    opponent: 'Sacramento Kings',
    score: '127-123',
    win: true,
    difference: 4,
    pointsMadeByCurry: 42,
  },
  {
    gameNumber: 41,
    date: '08 Jan 2019',
    venue: 'vs',
    opponent: 'New York Knicks',
    score: '122-95',
    win: true,
    difference: 27,
    pointsMadeByCurry: 14,
  },
  {
    gameNumber: 42,
    date: '11 Jan 2019',
    venue: 'vs',
    opponent: 'Chicago Bulls',
    score: '146-109',
    win: true,
    difference: 37,
    pointsMadeByCurry: 28,
  },
  {
    gameNumber: 43,
    date: '13 Jan 2019',
    venue: '@',
    opponent: 'Dallas Mavericks',
    score: '119-114',
    win: true,
    difference: 5,
    pointsMadeByCurry: 48,
  },
  {
    gameNumber: 44,
    date: '15 Jan 2019',
    venue: '@',
    opponent: 'Denver Nuggets',
    score: '142-111',
    win: true,
    difference: 31,
    pointsMadeByCurry: 31,
  },
  {
    gameNumber: 45,
    date: '16 Jan 2019',
    venue: 'vs',
    opponent: 'New Orleans Pelicans',
    score: '147-140',
    win: true,
    difference: 7,
    pointsMadeByCurry: 41,
  },
  {
    gameNumber: 46,
    date: '18 Jan 2019',
    venue: '@',
    opponent: 'LA Clippers',
    score: '112-94',
    win: true,
    difference: 18,
    pointsMadeByCurry: 28,
  },
  {
    gameNumber: 47,
    date: '21 Jan 2019',
    venue: '@',
    opponent: 'LA Lakers',
    score: '130-111',
    win: true,
    difference: 19,
    pointsMadeByCurry: 11,
  },
  {
    gameNumber: 48,
    date: '24 Jan 2019',
    venue: '@',
    opponent: 'Washington Wizards',
    score: '126-118',
    win: true,
    difference: 8,
    pointsMadeByCurry: 38,
  },
  {
    gameNumber: 49,
    date: '26 Jan 2019',
    venue: '@',
    opponent: 'Boston Celtics',
    score: '115-111',
    win: true,
    difference: 4,
    pointsMadeByCurry: 24,
  },
  {
    gameNumber: 50,
    date: '28 Jan 2019',
    venue: '@',
    opponent: 'Indiana Pacers',
    score: '132-100',
    win: true,
    difference: 32,
    pointsMadeByCurry: 26,
  },
  {
    gameNumber: 51,
    date: '31 Jan 2019',
    venue: 'vs',
    opponent: 'Philadelphia 76ers',
    score: '104-113',
    win: false,
    difference: 9,
    pointsMadeByCurry: 41,
  },
  {
    gameNumber: 52,
    date: '02 Feb 2019',
    venue: 'vs',
    opponent: 'LA Lakers',
    score: '115-101',
    win: true,
    difference: 14,
    pointsMadeByCurry: 14,
  },
  {
    gameNumber: 53,
    date: '06 Feb 2019',
    venue: 'vs',
    opponent: 'San Antonio Spurs',
    score: '141-102',
    win: true,
    difference: 39,
    pointsMadeByCurry: 19,
  },
  {
    gameNumber: 54,
    date: '08 Feb 2019',
    venue: '@',
    opponent: 'Phoenix Suns',
    score: '117-107',
    win: true,
    difference: 10,
    pointsMadeByCurry: 20,
  },
  {
    gameNumber: 55,
    date: '10 Feb 2019',
    venue: 'vs',
    opponent: 'Miami Heat',
    score: '120-118',
    win: true,
    difference: 2,
    pointsMadeByCurry: 25,
  },
  {
    gameNumber: 56,
    date: '12 Feb 2019',
    venue: 'vs',
    opponent: 'Utah Jazz',
    score: '115-108',
    win: true,
    difference: 7,
    pointsMadeByCurry: 24,
  },
  {
    gameNumber: 57,
    date: '13 Feb 2019',
    venue: '@',
    opponent: 'Portland Trail Blazers',
    score: '107-129',
    win: false,
    difference: 22,
    pointsMadeByCurry: 32,
  },
  {
    gameNumber: 58,
    date: '21 Feb 2019',
    venue: 'vs',
    opponent: 'Sacramento Kings',
    score: '125-123',
    win: true,
    difference: 2,
    pointsMadeByCurry: 36,
  },
  {
    gameNumber: 59,
    date: '23 Feb 2019',
    venue: 'vs',
    opponent: 'Houston Rockets',
    score: '112-118',
    win: false,
    difference: 6,
    pointsMadeByCurry: 25,
  },
  {
    gameNumber: 60,
    date: '25 Feb 2019',
    venue: '@',
    opponent: 'Charlotte Hornets',
    score: '121-110',
    win: true,
    difference: 11,
    pointsMadeByCurry: 16,
  },
  {
    gameNumber: 61,
    date: '27 Feb 2019',
    venue: '@',
    opponent: 'Miami Heat',
    score: '125-126',
    win: false,
    difference: 1,
    pointsMadeByCurry: 24,
  },
  {
    gameNumber: 62,
    date: '28 Feb 2019',
    venue: '@',
    opponent: 'Orlando Magic',
    score: '96-103',
    win: false,
    difference: 7,
    pointsMadeByCurry: 33,
  },
  {
    gameNumber: 63,
    date: '02 Mar 2019',
    venue: '@',
    opponent: 'Philadelphia 76ers',
    score: '120-117',
    win: true,
    difference: 3,
    pointsMadeByCurry: 28,
  },
  {
    gameNumber: 64,
    date: '05 Mar 2019',
    venue: 'vs',
    opponent: 'Boston Celtics',
    score: '95-128',
    win: false,
    difference: 33,
    pointsMadeByCurry: 23,
  },
  {
    gameNumber: 65,
    date: '08 Mar 2019',
    venue: 'vs',
    opponent: 'Denver Nuggets',
    score: '122-105',
    win: true,
    difference: 17,
    pointsMadeByCurry: 17,
  },
  {
    gameNumber: 66,
    date: '10 Mar 2019',
    venue: 'vs',
    opponent: 'Phoenix Suns',
    score: '111-115',
    win: false,
    difference: 4,
    pointsMadeByCurry: 18,
  },
  {
    gameNumber: 67,
    date: '13 Mar 2019',
    venue: '@',
    opponent: 'Houston Rockets',
    score: '106-104',
    win: true,
    difference: 2,
    pointsMadeByCurry: 24,
  },
  {
    gameNumber: 68,
    date: '16 Mar 2019',
    venue: '@',
    opponent: 'Oklahoma City Thunder',
    score: '110-88',
    win: true,
    difference: 22,
    pointsMadeByCurry: 33,
  },
  {
    gameNumber: 69,
    date: '18 Mar 2019',
    venue: '@',
    opponent: 'San Antonio Spurs',
    score: '105-111',
    win: false,
    difference: 6,
    pointsMadeByCurry: 25,
  },
  {
    gameNumber: 70,
    date: '19 Mar 2019',
    venue: '@',
    opponent: 'Minnesota Timberwolves',
    score: '117-107',
    win: true,
    difference: 10,
    pointsMadeByCurry: 36,
  },
  {
    gameNumber: 71,
    date: '21 Mar 2019',
    venue: 'vs',
    opponent: 'Indiana Pacers',
    score: '112-89',
    win: true,
    difference: 23,
    pointsMadeByCurry: 15,
  },
  {
    gameNumber: 72,
    date: '23 Mar 2019',
    venue: 'vs',
    opponent: 'Dallas Mavericks',
    score: '91-126',
    win: false,
    difference: 35,
    pointsMadeByCurry: 0,
  },
  {
    gameNumber: 73,
    date: '24 Mar 2019',
    venue: 'vs',
    opponent: 'Detroit Pistons',
    score: '121-114',
    win: true,
    difference: 7,
    pointsMadeByCurry: 26,
  },
  {
    gameNumber: 74,
    date: '27 Mar 2019',
    venue: '@',
    opponent: 'Memphis Grizzlies',
    score: '118-103',
    win: true,
    difference: 15,
    pointsMadeByCurry: 28,
  },
  {
    gameNumber: 75,
    date: '29 Mar 2019',
    venue: '@',
    opponent: 'Minnesota Timberwolves',
    score: '130-131',
    win: false,
    difference: 1,
    pointsMadeByCurry: 37,
  },
  {
    gameNumber: 76,
    date: '31 Mar 2019',
    venue: 'vs',
    opponent: 'Charlotte Hornets',
    score: '137-90',
    win: true,
    difference: 47,
    pointsMadeByCurry: 25,
  },
  {
    gameNumber: 77,
    date: '02 Apr 2019',
    venue: 'vs',
    opponent: 'Denver Nuggets',
    score: '106-102',
    win: true,
    difference: 4,
    pointsMadeByCurry: 17,
  },
  {
    gameNumber: 78,
    date: '04 Apr 2019',
    venue: '@',
    opponent: 'LA Lakers',
    score: '108-90',
    win: true,
    difference: 18,
    pointsMadeByCurry: 7,
  },
  {
    gameNumber: 79,
    date: '05 Apr 2019',
    venue: 'vs',
    opponent: 'Cleveland Cavaliers',
    score: '120-114',
    win: true,
    difference: 6,
    pointsMadeByCurry: 40,
  },
  {
    gameNumber: 80,
    date: '07 Apr 2019',
    venue: 'vs',
    opponent: 'LA Clippers',
    score: '131-104',
    win: true,
    difference: 27,
    pointsMadeByCurry: 27,
  },
  {
    gameNumber: 81,
    date: '09 Apr 2019',
    venue: '@',
    opponent: 'New Orleans Pelicans',
    score: '112-103',
    win: true,
    difference: 9,
    pointsMadeByCurry: 5,
  },
  {
    gameNumber: 82,
    date: '10 Apr 2019',
    venue: '@',
    opponent: 'Memphis Grizzlies',
    score: '117-132',
    win: false,
    difference: 15,
    pointsMadeByCurry: 0,
  },
];
